config/routes.rb
ListingScraper::Application.routes.draw do
  resources :landlords

  resources :listings

  

end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
  has_many :listings, dependent: :destroy
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :landlord
  has_many :photos, dependent: :destroy
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :listing
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  before_action :set_landlord, only: [:show, :edit, :update, :destroy]

  # GET /landlords
  # GET /landlords.json
  def index
    @landlords = Landlord.all
  end

  # GET /landlords/1
  # GET /landlords/1.json
  def show
  end

  # GET /landlords/new
  def new
    @landlord = Landlord.new
  end

  # GET /landlords/1/edit
  def edit
  end

  # POST /landlords
  # POST /landlords.json
  def create
    @landlord = Landlord.new(landlord_params)

    respond_to do |format|
      if @landlord.save
        format.html { redirect_to @landlord, notice: 'Landlord was successfully created.' }
        format.json { render action: 'show', status: :created, location: @landlord }
      else
        format.html { render action: 'new' }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landlords/1
  # PATCH/PUT /landlords/1.json
  def update
    respond_to do |format|
      if @landlord.update(landlord_params)
        format.html { redirect_to @landlord, notice: 'Landlord was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1
  # DELETE /landlords/1.json
  def destroy
    @landlord.destroy
    respond_to do |format|
      format.html { redirect_to landlords_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landlord
      @landlord = Landlord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landlord_params
      params.require(:landlord).permit(:company_id, :website, :name, :address, :city, :state, :postal_code, :country)
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:short_description, :long_description, :bedroom_count, :bathroom_count, :price, :website, :name, :deposit, :square_feet, :year_built, :pet_policy, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/landlords/_form.html.erb
<%= form_for(@landlord) do |f| %>
  <% if @landlord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@landlord.errors.count, "error") %> prohibited this landlord from being saved:</h2>

      <ul>
      <% @landlord.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.text_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.number_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/landlords/edit.html.erb
<h1>Editing landlord</h1>

<%= render 'form' %>

<%= link_to 'Show', @landlord %> |
<%= link_to 'Back', landlords_path %>

app/views/landlords/index.html.erb
<h1>Listing landlords</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Website</th>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Postal code</th>
      <th>Country</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @landlords.each do |landlord| %>
      <tr>
        <td><%= landlord.company_id %></td>
        <td><%= landlord.website %></td>
        <td><%= landlord.name %></td>
        <td><%= landlord.address %></td>
        <td><%= landlord.city %></td>
        <td><%= landlord.state %></td>
        <td><%= landlord.postal_code %></td>
        <td><%= landlord.country %></td>
        <td><%= link_to 'Show', landlord %></td>
        <td><%= link_to 'Edit', edit_landlord_path(landlord) %></td>
        <td><%= link_to 'Destroy', landlord, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Landlord', new_landlord_path %>

app/views/landlords/new.html.erb
<h1>New landlord</h1>

<%= render 'form' %>

<%= link_to 'Back', landlords_path %>

app/views/landlords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @landlord.company_id %>
</p>

<p>
  <strong>Website:</strong>
  <%= @landlord.website %>
</p>

<p>
  <strong>Name:</strong>
  <%= @landlord.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @landlord.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @landlord.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @landlord.state %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @landlord.postal_code %>
</p>

<p>
  <strong>Country:</strong>
  <%= @landlord.country %>
</p>

<%= link_to 'Edit', edit_landlord_path(@landlord) %> |
<%= link_to 'Back', landlords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ListingScraper</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_field :short_description %>
  </div>
  <div class="field">
    <%= f.label :long_description %><br>
    <%= f.text_field :long_description %>
  </div>
  <div class="field">
    <%= f.label :bedroom_count %><br>
    <%= f.number_field :bedroom_count %>
  </div>
  <div class="field">
    <%= f.label :bathroom_count %><br>
    <%= f.number_field :bathroom_count %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :deposit %><br>
    <%= f.text_field :deposit %>
  </div>
  <div class="field">
    <%= f.label :square_feet %><br>
    <%= f.number_field :square_feet %>
  </div>
  <div class="field">
    <%= f.label :year_built %><br>
    <%= f.number_field :year_built %>
  </div>
  <div class="field">
    <%= f.label :pet_policy %><br>
    <%= f.check_box :pet_policy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <thead>
    <tr>
      <th>Short description</th>
      <th>Long description</th>
      <th>Bedroom count</th>
      <th>Bathroom count</th>
      <th>Price</th>
      <th>Website</th>
      <th>Name</th>
      <th>Deposit</th>
      <th>Square feet</th>
      <th>Year built</th>
      <th>Pet policy</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.short_description %></td>
        <td><%= listing.long_description %></td>
        <td><%= listing.bedroom_count %></td>
        <td><%= listing.bathroom_count %></td>
        <td><%= listing.price %></td>
        <td><%= listing.website %></td>
        <td><%= listing.name %></td>
        <td><%= listing.deposit %></td>
        <td><%= listing.square_feet %></td>
        <td><%= listing.year_built %></td>
        <td><%= listing.pet_policy %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short description:</strong>
  <%= @listing.short_description %>
</p>

<p>
  <strong>Long description:</strong>
  <%= @listing.long_description %>
</p>

<p>
  <strong>Bedroom count:</strong>
  <%= @listing.bedroom_count %>
</p>

<p>
  <strong>Bathroom count:</strong>
  <%= @listing.bathroom_count %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Website:</strong>
  <%= @listing.website %>
</p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Deposit:</strong>
  <%= @listing.deposit %>
</p>

<p>
  <strong>Square feet:</strong>
  <%= @listing.square_feet %>
</p>

<p>
  <strong>Year built:</strong>
  <%= @listing.year_built %>
</p>

<p>
  <strong>Pet policy:</strong>
  <%= @listing.pet_policy %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>